# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be828982041a8e266bb5ec482146a17fb1dc845d860e6fb9f6c27b770a0dada40641007a65bca2f359f0e55ff44666e6670f9f108a9a2060d97b924f26e6a00b

test:
  secret_key_base: 9c5c2b4c187c1b12974dfbe32f72c204f773b9417d47e49eae58fc15d1bf991a814c6dfc9a2cab02e79c8948a764045b6d7d7bcefca8f45103cd0b8f0292d3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
